Repository Interview-Bank/Interview-Bank-Back, pull requests merged in 2023-05, with the labels that each got.

#210 [Fix] modify build timezone
  Dockerfile
Labels: fix

#212 [Fix] Modify Search Category
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
Labels: fix

#214 [Feat] create interview gpt
  src/main/java/org/hoongoin/interviewbank/common/discord/DiscordHandler.java
  src/main/java/org/hoongoin/interviewbank/common/gpt/GptRequestBody.java
  src/main/java/org/hoongoin/interviewbank/common/gpt/GptRequestHandler.java
  src/main/java/org/hoongoin/interviewbank/common/gpt/GptResponseBody.java
  src/main/java/org/hoongoin/interviewbank/common/gpt/MessageRole.java
  src/main/java/org/hoongoin/interviewbank/interview/InterviewMapper.java
  src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
  src/main/java/org/hoongoin/interviewbank/interview/application/entity/Question.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/CreateInterviewAndQuestionsResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/FindInterviewResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandService.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/entity/QuestionEntity.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-secret.yml
  src/main/resources/application-staging.yml
  src/main/resources/schema.sql
  src/test/java/org/hoongoin/interviewbank/config/TestMockConfig.java
  src/test/java/org/hoongoin/interviewbank/gpt/GptResponseBodyFactory.java
  src/test/java/org/hoongoin/interviewbank/interview/application/InterviewServiceTest.java
  src/test/java/org/hoongoin/interviewbank/interview/controller/InterviewControllerTest.java
  src/test/resources/application-test.yml
  src/test/resources/schema-test.sql
Labels: feature

#217 [Fix] incorrect question id response
  src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
Labels: bug, fix

#216 [Feat] update interview gpt
  src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/UpdateInterviewResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandService.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandServiceAsync.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/entity/QuestionEntity.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/QuestionRepository.java
  src/test/java/org/hoongoin/interviewbank/interview/controller/InterviewControllerTest.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandServiceTest.java
Labels: feature

#220 [Feat] delete scrap
  src/main/java/org/hoongoin/interviewbank/scrap/application/ScrapService.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/ScrapController.java
Labels: feature
