Repository Interview-Bank/Interview-Bank-Back, pull requests merged in 2023-03, with the labels that each got.

#80 [Chore] PR Title Validation
  .github/workflows/pr_title_validation.yml
Labels: feature

#78 [Fix] redis key store byte to string
  src/main/java/org/hoongoin/interviewbank/config/RedisConfig.java
Labels: fix

#81 [Chore] Run Test Code When Merge
  .github/workflows/run_test_code.yml
Labels: feature

#85 [Docs] Fix PR Template File Name
  .github/pull_request_template.md
Labels: bug, documentation

#87 [Fix] Apply Soft Delete
  src/main/java/org/hoongoin/interviewbank/account/domain/AccountQueryService.java
  src/main/java/org/hoongoin/interviewbank/exception/IbAccountNotMatchException.java
  src/main/java/org/hoongoin/interviewbank/exception/IbSoftDeleteException.java
  src/main/java/org/hoongoin/interviewbank/exception/handler/IbControllerAdvice.java
  src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewCommandService.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/QuestionRepository.java
  src/test/java/org/hoongoin/interviewbank/interview/application/InterviewServiceTest.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/InterviewEntityCommandServiceTest.java
Labels: fix

#89 [Fix] Springfox Swagger Server URL
  src/main/java/org/hoongoin/interviewbank/config/SpringfoxSwaggerBasePathResolver.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-staging.yml
Labels: fix

#91 fix: add discord staging channel
  staging.env
Labels: fix

#93 [Fix] add swagger server url to application-test.yml
  src/test/resources/application-test.yml
Labels: bug, fix

#92 [Chore] PR Template and Git Branch Rule
  .github/pull_request_template.md
  .github/workflows/pr_title_validation.yml
  .github/workflows/run_test_code.yml
Labels: documentation, feature

#95 [Test] scrap service unit test
  src/main/java/org/hoongoin/interviewbank/scrap/controller/response/ScrapQuestionWithScrapAnswersResponse.java
  src/test/java/org/hoongoin/interviewbank/scrap/application/ScrapServiceTest.java
Labels: test

#97 [Test] API Authentication Test
  src/main/java/org/hoongoin/interviewbank/config/SecurityConfig.java
  src/test/java/org/hoongoin/interviewbank/authentication/AccountApiAuthentication.java
  src/test/java/org/hoongoin/interviewbank/authentication/InterviewApiAuthentication.java
  src/test/java/org/hoongoin/interviewbank/authentication/ScrapAnswerApiAuthentication.java
  src/test/java/org/hoongoin/interviewbank/authentication/ScrapApiAuthentication.java
  src/test/java/org/hoongoin/interviewbank/config/IbWithMockUserSecurityContextFactory.java
  src/test/java/org/hoongoin/interviewbank/config/TestRedisConfig.java
Labels: help wanted, test

#101 [Refactor] Controller
  src/main/java/org/hoongoin/interviewbank/account/controller/AccountController.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/ScrapAnswerController.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/ScrapController.java
Labels: refactor

#102 [Feat] OAuth Login And Register
  src/main/java/org/hoongoin/interviewbank/account/AccountMapper.java
  src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
  src/main/java/org/hoongoin/interviewbank/account/application/GoogleOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/KakaoOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/NaverOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleTokenRequestParams.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleTokenResponse.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleUerInfo.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/KakaoTokenRequestParams.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/KakaoTokenResponse.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/KakaoUerInfoResponse.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/NaverTokenRequestParams.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/NaverTokenResponse.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/NaverUserInfoResponse.java
  src/main/java/org/hoongoin/interviewbank/account/application/entity/Account.java
  src/main/java/org/hoongoin/interviewbank/account/controller/AccountController.java
  src/main/java/org/hoongoin/interviewbank/account/controller/GoogleOAuthController.java
  src/main/java/org/hoongoin/interviewbank/account/controller/KakaoOAuthController.java
  src/main/java/org/hoongoin/interviewbank/account/controller/NaverOAuthController.java
  src/main/java/org/hoongoin/interviewbank/account/controller/request/GoogleRegister.java
  src/main/java/org/hoongoin/interviewbank/account/domain/AccountCommandService.java
  src/main/java/org/hoongoin/interviewbank/account/infrastructure/entity/AccountEntity.java
  src/main/java/org/hoongoin/interviewbank/account/infrastructure/entity/AccountType.java
  src/main/java/org/hoongoin/interviewbank/account/infrastructure/repository/AccountRepository.java
  src/main/java/org/hoongoin/interviewbank/scrap/infrastructure/entity/ScrapQuestionEntity.java
  src/main/java/org/hoongoin/interviewbank/utils/SecurityUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-secret.yml
  src/main/resources/application-staging.yml
  src/main/resources/schema.sql
  src/test/resources/application-test.yml
  src/test/resources/schema-test.sql
Labels: help wanted, feature

#104 [Fix] Add 1 git-crypt collaborator
  .git-crypt/keys/default/0/0C018DFF3EEA9AB7DAD4BADF97B6CA5A0A7A521E.gpg
Labels: fix

#105 [Refactor] Formatting
  src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleTokenRequestParams.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleTokenResponse.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleUerInfo.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/KakaoTokenRequestParams.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/KakaoTokenResponse.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/KakaoUerInfoResponse.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/NaverTokenRequestParams.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/NaverTokenResponse.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/NaverUserInfoResponse.java
  src/main/java/org/hoongoin/interviewbank/account/controller/request/GoogleRegister.java
  src/main/java/org/hoongoin/interviewbank/account/controller/request/LoginRequest.java
  src/main/java/org/hoongoin/interviewbank/account/controller/request/RegisterRequest.java
  src/main/java/org/hoongoin/interviewbank/account/infrastructure/repository/AccountRepository.java
  src/main/java/org/hoongoin/interviewbank/common/entity/BaseEntity.java
  src/main/java/org/hoongoin/interviewbank/common/entity/SoftDeletedBaseEntity.java
  src/main/java/org/hoongoin/interviewbank/config/IbAuthenticationEntryPoint.java
  src/main/java/org/hoongoin/interviewbank/config/SecurityConfig.java
  src/main/java/org/hoongoin/interviewbank/config/SpringfoxSwaggerBasePathResolver.java
  src/main/java/org/hoongoin/interviewbank/config/SwaggerConfiguration.java
  src/main/java/org/hoongoin/interviewbank/exception/IbPasswordNotMatchException.java
  src/main/java/org/hoongoin/interviewbank/exception/IbSoftDeleteException.java
  src/main/java/org/hoongoin/interviewbank/exception/IbUnauthorizedException.java
  src/main/java/org/hoongoin/interviewbank/exception/IbValidationException.java
  src/main/java/org/hoongoin/interviewbank/exception/handler/IbControllerAdvice.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/request/QuestionsRequest.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/request/UpdateInterviewRequest.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/CreateInterviewAndQuestionsResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/FindInterviewResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/UpdateInterviewResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandService.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/entity/InterviewEntity.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/entity/QuestionEntity.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/QuestionRepository.java
  src/main/java/org/hoongoin/interviewbank/scrap/ScrapMapper.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/ScrapService.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/entity/ScrapQuestionWithScrapAnswers.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/ScrapAnswerController.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/ScrapController.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/response/ScrapQuestionWithScrapAnswersResponse.java
  src/main/java/org/hoongoin/interviewbank/scrap/infrastructure/entity/ScrapAnswerEntity.java
  src/main/java/org/hoongoin/interviewbank/scrap/infrastructure/entity/ScrapEntity.java
  src/main/java/org/hoongoin/interviewbank/scrap/infrastructure/entity/ScrapQuestionEntity.java
  src/main/java/org/hoongoin/interviewbank/utils/MessageFactory.java
  src/main/java/org/hoongoin/interviewbank/utils/SecurityUtil.java
  src/main/resources/application.yml
  src/test/java/org/hoongoin/interviewbank/authentication/AccountApiAuthentication.java
  src/test/java/org/hoongoin/interviewbank/authentication/InterviewApiAuthentication.java
  src/test/java/org/hoongoin/interviewbank/authentication/ScrapAnswerApiAuthentication.java
  src/test/java/org/hoongoin/interviewbank/authentication/ScrapApiAuthentication.java
  src/test/java/org/hoongoin/interviewbank/config/TestRedisConfig.java
  src/test/java/org/hoongoin/interviewbank/interview/application/InterviewServiceTest.java
  src/test/java/org/hoongoin/interviewbank/interview/controller/InterviewControllerTest.java
  src/test/java/org/hoongoin/interviewbank/interview/infrastructure/entity/InterviewEntityTest.java
  src/test/java/org/hoongoin/interviewbank/scrap/application/ScrapServiceTest.java
  src/test/java/org/hoongoin/interviewbank/scrap/controller/ScrapControllerTest.java
Labels: refactor

#107 [Refactor] error response message
  src/main/java/org/hoongoin/interviewbank/exception/handler/IbControllerAdvice.java
Labels: refactor

#106 [Fix] google oauth
  .gitignore
  build.gradle
  src/main/java/org/hoongoin/interviewbank/account/application/GoogleOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/NaverOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleTokenResponse.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleUerInfo.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/NaverProfileResponse.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/NaverUserInfoResponse.java
  src/main/java/org/hoongoin/interviewbank/account/controller/GoogleOAuthController.java
  src/main/java/org/hoongoin/interviewbank/account/controller/NaverOAuthController.java
  src/main/java/org/hoongoin/interviewbank/account/domain/AccountCommandService.java
  src/main/java/org/hoongoin/interviewbank/exception/IbInternalServerException.java
  src/main/java/org/hoongoin/interviewbank/exception/handler/IbControllerAdvice.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-secret.yml
  src/main/resources/application-staging.yml
  src/test/resources/application-test.yml
Labels: fix

#108 [Fix] Add Jenkins User 1 git-crypt collaborator
  .git-crypt/keys/default/0/96623D17B302052D7A373BDA0002010BDD555CCA.gpg
Labels: fix

#110 [Feat] Add jenkins-trigger.sh file
  jenkins-trigger.sh
Labels: feature

#120 [Fix] Fix Question Query
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/QuestionRepository.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionQueryServiceTest.java
Labels: fix

#122 [Fix] Fix FindInterview Logic Order By Asc to Desc
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
Labels: fix

#123 [Refactor] email or password incorrect exception
  src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
  src/main/java/org/hoongoin/interviewbank/account/domain/AccountQueryService.java
  src/main/java/org/hoongoin/interviewbank/exception/IbLoginFailedException.java
  src/main/java/org/hoongoin/interviewbank/exception/IbPasswordNotMatchException.java
  src/main/java/org/hoongoin/interviewbank/exception/handler/IbControllerAdvice.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/ScrapAnswerService.java
Labels: refactor

#126 [Fix] one scrap answer
  src/main/java/org/hoongoin/interviewbank/scrap/ScrapMapper.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/ScrapAnswerService.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/ScrapService.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/entity/ScrapAnswer.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/entity/ScrapQuestionAndScrapAnswer.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/entity/ScrapWithScrapQuestionAndScrapAnswerList.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/ScrapAnswerController.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/ScrapController.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/response/CreateScrapResponse.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/response/ScrapAnswerResponse.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/response/ScrapQuestionAndScrapAnswerResponse.java
  src/main/java/org/hoongoin/interviewbank/scrap/domain/ScrapAnswerCommandService.java
  src/main/java/org/hoongoin/interviewbank/scrap/domain/ScrapCommandService.java
  src/test/java/org/hoongoin/interviewbank/authentication/ScrapAnswerApiAuthentication.java
  src/test/java/org/hoongoin/interviewbank/scrap/application/ScrapServiceTest.java
  src/test/java/org/hoongoin/interviewbank/scrap/controller/ScrapControllerTest.java
Labels: bug, fix

#128 [Feat] Introduce Monitoring tool
  .gitattributes
  build.gradle
  interview_bank_docker/docker-compose-staging.yaml
  jenkins-trigger.sh
  nginx/staging/staging.conf
  src/main/java/org/hoongoin/interviewbank/config/ActuatorConfig.java
  src/main/resources/application-staging.yml
  staging-yml/grafana.ini
  staging-yml/prometheus.yml
Labels: feature

#130 [Fix] Google OAuth
  build.gradle
  src/main/java/org/hoongoin/interviewbank/account/application/GoogleOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleJwtPayload.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleTokenRequestParams.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleTokenResponse.java
  src/main/java/org/hoongoin/interviewbank/account/application/entity/Account.java
  src/main/java/org/hoongoin/interviewbank/account/controller/GoogleOAuthController.java
Labels: bug, fix

#132 [Fix] google oauth user
  src/main/java/org/hoongoin/interviewbank/account/domain/AccountCommandService.java
  src/main/resources/schema.sql
  src/test/resources/schema-test.sql
Labels: bug, fix

#133 [Fix] Naver OAuth Error Query Required False
  src/main/java/org/hoongoin/interviewbank/account/controller/NaverOAuthController.java
Labels: bug, fix
