Repository Interview-Bank/Interview-Bank-Back, pull requests merged in 2023-04, with the labels that each got.

#135 [Feat] Inquiry
  src/main/java/org/hoongoin/interviewbank/inquiry/InquiryMapper.java
  src/main/java/org/hoongoin/interviewbank/inquiry/application/InquiryService.java
  src/main/java/org/hoongoin/interviewbank/inquiry/application/entity/Inquiry.java
  src/main/java/org/hoongoin/interviewbank/inquiry/controller/InquiryController.java
  src/main/java/org/hoongoin/interviewbank/inquiry/controller/request/InquiryRequest.java
  src/main/java/org/hoongoin/interviewbank/inquiry/domain/InquiryCommandService.java
  src/main/java/org/hoongoin/interviewbank/inquiry/infrastructure/InquiryRepository.java
  src/main/java/org/hoongoin/interviewbank/inquiry/infrastructure/entity/InquiryEntity.java
  src/main/resources/schema.sql
  src/test/resources/schema-test.sql
Labels: feature

#138 [Fix] naver oauth redirect error null
  src/main/java/org/hoongoin/interviewbank/account/controller/NaverOAuthController.java
Labels: bug, fix

#139 [Fix] naver oauth converter
  src/main/java/org/hoongoin/interviewbank/account/application/NaverOAuthService.java
Labels: bug, fix

#137 [Feat] Implement db-backup
  db-backup/Dockerfile
  db-backup/backup.sh
  interview_bank_docker/docker-compose-local.yaml
  interview_bank_docker/docker-compose-staging.yaml
Labels: feature

#150 [Fix] account kakao and email password
  src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
  src/main/java/org/hoongoin/interviewbank/account/domain/AccountCommandService.java
  src/main/java/org/hoongoin/interviewbank/account/domain/AccountQueryService.java
  src/test/java/org/hoongoin/interviewbank/account/controller/AccountControllerTest.java
Labels: bug, fix

#152 [Fix] DB schema
  src/main/java/org/hoongoin/interviewbank/inquiry/infrastructure/entity/InquiryEntity.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/entity/JobCategoryEntity.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/entity/QuestionEntity.java
  src/main/java/org/hoongoin/interviewbank/scrap/infrastructure/entity/ScrapAnswerEntity.java
  src/main/java/org/hoongoin/interviewbank/scrap/infrastructure/entity/ScrapEntity.java
  src/main/java/org/hoongoin/interviewbank/scrap/infrastructure/entity/ScrapQuestionEntity.java
  src/main/resources/schema.sql
  src/test/resources/schema-test.sql
Labels: fix

#155 [Feat] get job category api
  src/main/java/org/hoongoin/interviewbank/interview/JobCategoryService.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/JobCategoryController.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/GetJobCategoryResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/JobCategoryQueryService.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/JobCategoryQueryServiceImplementation.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/entity/JobCategoryWithHierarchy.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/entity/JobCategoryWithParentNameAndChildName.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/JobCategoryRepository.java
  src/main/resources/data.sql
Labels: feature

#154 [Feat] Implement interview attributes
  src/main/java/org/hoongoin/interviewbank/interview/InterviewMapper.java
  src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
  src/main/java/org/hoongoin/interviewbank/interview/application/dto/InterviewModifyDto.java
  src/main/java/org/hoongoin/interviewbank/interview/application/entity/Interview.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/request/CreateInterviewAndQuestionsRequest.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/request/UpdateInterviewRequest.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/CreateInterviewAndQuestionsResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/FindInterviewPageResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/FindInterviewResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/UpdateInterviewResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewCommandService.java
  src/main/java/org/hoongoin/interviewbank/interview/enums/CareerYear.java
  src/main/java/org/hoongoin/interviewbank/interview/enums/InterviewPeriod.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/entity/InterviewEntity.java
  src/main/resources/schema.sql
  src/test/java/org/hoongoin/interviewbank/interview/application/InterviewServiceTest.java
  src/test/java/org/hoongoin/interviewbank/interview/controller/InterviewControllerTest.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/InterviewEntityCommandServiceTest.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandServiceTest.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionQueryServiceTest.java
Labels: feature

#158 [Feat] my interview
  src/main/java/org/hoongoin/interviewbank/interview/InterviewMapper.java
  src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/FindMyInterviewResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
  src/test/java/org/hoongoin/interviewbank/interview/application/InterviewServiceTest.java
Labels: feature

#156 [Fix] add job category in reading interview
  src/main/java/org/hoongoin/interviewbank/interview/InterviewMapper.java
  src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
  src/main/java/org/hoongoin/interviewbank/interview/application/entity/Interview.java
  src/main/java/org/hoongoin/interviewbank/interview/application/entity/JobCategory.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/request/CreateInterviewAndQuestionsRequest.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/request/UpdateInterviewRequest.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/CreateInterviewAndQuestionsResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/FindInterviewPageResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/FindInterviewResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/JobCategoryResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/UpdateInterviewResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewCommandService.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/JobCategoryQueryService.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/JobCategoryQueryServiceImplementation.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/entity/InterviewEntity.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/JobCategoryRepository.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/test/java/org/hoongoin/interviewbank/interview/application/InterviewServiceTest.java
  src/test/java/org/hoongoin/interviewbank/interview/controller/InterviewControllerTest.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/InterviewEntityCommandServiceTest.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandServiceTest.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionQueryServiceTest.java
  src/test/resources/job-category-data.sql
  src/test/resources/schema-test.sql
Labels: fix

#160 [Fix] swap job category level
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/JobCategoryRepository.java
Labels: bug, fix

#161 [Fix] job category multi select
  src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
Labels: fix

#163 [Feat] Get My Account
  src/main/java/org/hoongoin/interviewbank/account/AccountMapper.java
  src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
  src/main/java/org/hoongoin/interviewbank/account/application/entity/Account.java
  src/main/java/org/hoongoin/interviewbank/account/controller/AccountController.java
  src/main/java/org/hoongoin/interviewbank/account/controller/response/GetMeResponse.java
  src/main/java/org/hoongoin/interviewbank/account/domain/AccountCommandService.java
  src/main/java/org/hoongoin/interviewbank/account/infrastructure/entity/AccountEntity.java
  src/main/java/org/hoongoin/interviewbank/config/SecurityConfig.java
  src/main/resources/schema.sql
  src/test/java/org/hoongoin/interviewbank/authentication/AccountApiAuthentication.java
  src/test/resources/schema-test.sql
Labels: feature

#166 [Feat] My Profile Image
  build.gradle
  src/main/java/org/hoongoin/interviewbank/account/AccountMapper.java
  src/main/java/org/hoongoin/interviewbank/account/application/AccountExternalService.java
  src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
  src/main/java/org/hoongoin/interviewbank/account/application/GoogleOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/NaverOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/entity/Account.java
  src/main/java/org/hoongoin/interviewbank/account/controller/AccountController.java
  src/main/java/org/hoongoin/interviewbank/account/controller/response/UploadProfileImageResponse.java
  src/main/java/org/hoongoin/interviewbank/account/domain/AccountCommandService.java
  src/main/java/org/hoongoin/interviewbank/account/infrastructure/entity/AccountEntity.java
  src/main/java/org/hoongoin/interviewbank/config/AmazonS3Config.java
  src/main/resources/application-secret.yml
  src/main/resources/schema.sql
  src/test/java/org/hoongoin/interviewbank/config/TestMockConfig.java
  src/test/resources/application-test.yml
  src/test/resources/schema-test.sql
Labels: feature

#170 [Fix] Aws Iam Authoirty
  src/main/resources/application-secret.yml
  src/test/resources/application-test.yml
Labels: fix

#171 [Fix] job category multi select
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
Labels: bug, fix

#172 [Refactor] Google OAuth Separate Properties
  build.gradle
  src/main/java/org/hoongoin/interviewbank/InterviewbankApplication.java
  src/main/java/org/hoongoin/interviewbank/account/application/GoogleOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/GoogleOAuthProperties.java
  src/main/java/org/hoongoin/interviewbank/account/controller/GoogleOAuthController.java
  src/main/java/org/hoongoin/interviewbank/config/RestTemplateConfig.java
Labels: refactor

#173 [Fix] google oauth uri null
  src/main/resources/application-secret.yml
  src/test/java/org/hoongoin/interviewbank/account/application/GoogleOAuthServiceTest.java
  src/test/resources/application-test.yml
Labels: bug, fix

#175 [Refactor] kakao oauth
  src/main/java/org/hoongoin/interviewbank/InterviewbankApplication.java
  src/main/java/org/hoongoin/interviewbank/account/application/KakaoOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/KakaoOAuthProperties.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/KakaoTokenResponse.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/KakaoUserInfoResponse.java
  src/main/java/org/hoongoin/interviewbank/account/controller/KakaoOAuthController.java
  src/main/java/org/hoongoin/interviewbank/account/domain/AccountCommandService.java
Labels: refactor

#178 [Fix] Modify Profile Image API
  src/main/java/org/hoongoin/interviewbank/account/controller/AccountController.java
  src/main/java/org/hoongoin/interviewbank/account/controller/response/GetMeResponse.java
  src/main/java/org/hoongoin/interviewbank/account/controller/response/LoginResponse.java
Labels: fix

#181 [Fix] Delete log filter and Modify timezone
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-staging.yml
  src/main/resources/logback-spring.xml
Labels: bug, fix

#182 [Fix] add interview period to interview search
  src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
Labels: fix

#185 [Feat] reset password when logged in
  src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
  src/main/java/org/hoongoin/interviewbank/account/controller/AccountController.java
  src/main/java/org/hoongoin/interviewbank/config/SecurityConfig.java
  src/test/java/org/hoongoin/interviewbank/authentication/AccountApiAuthentication.java
Labels: feature

#187 [Fix] interview me add job category
  src/main/java/org/hoongoin/interviewbank/interview/InterviewMapper.java
  src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/FindMyInterviewResponse.java
  src/test/java/org/hoongoin/interviewbank/interview/application/InterviewServiceTest.java
Labels: fix

#184 [Fix] scrap job category
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewCommandService.java
  src/main/java/org/hoongoin/interviewbank/scrap/ScrapMapper.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/ScrapService.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/entity/Scrap.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/ScrapController.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/response/ReadScrapResponse.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/response/ScrapResponse.java
  src/main/java/org/hoongoin/interviewbank/scrap/domain/ScrapCommandService.java
  src/main/java/org/hoongoin/interviewbank/scrap/infrastructure/entity/ScrapEntity.java
  src/main/resources/schema.sql
  src/test/java/org/hoongoin/interviewbank/interview/domain/InterviewEntityCommandServiceTest.java
  src/test/java/org/hoongoin/interviewbank/scrap/application/ScrapServiceTest.java
  src/test/java/org/hoongoin/interviewbank/scrap/controller/ScrapControllerTest.java
  src/test/resources/schema-test.sql
Labels: fix

#191 [Fix] Add profile-image null And Implement initialize profile image
  src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
  src/main/java/org/hoongoin/interviewbank/account/controller/AccountController.java
  src/main/java/org/hoongoin/interviewbank/account/controller/response/InitializeProfileImageResponse.java
  src/main/resources/schema.sql
  src/test/resources/schema-test.sql
Labels: fix

#193 [Fix] page response
  src/main/java/org/hoongoin/interviewbank/common/dto/PageDto.java
  src/main/java/org/hoongoin/interviewbank/exception/handler/IbControllerAdvice.java
  src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/FindInterviewPageResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
  src/main/java/org/hoongoin/interviewbank/scrap/ScrapMapper.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/ScrapService.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/ScrapController.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/response/ReadScrapPageResponse.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/response/ReadScrapResponse.java
  src/main/java/org/hoongoin/interviewbank/scrap/domain/ScrapQueryService.java
  src/main/java/org/hoongoin/interviewbank/scrap/infrastructure/repository/ScrapRepository.java
Labels: fix

#196 [Refactor] oauth
  src/main/java/org/hoongoin/interviewbank/InterviewbankApplication.java
  src/main/java/org/hoongoin/interviewbank/account/application/KakaoOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/NaverOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/dto/NaverOAuthProperties.java
Labels: refactor

#197 [Fix] naver oauth properties
  src/main/resources/application-secret.yml
Labels: bug, fix

#198 [Fix] naver oauth get profile response
  src/main/java/org/hoongoin/interviewbank/account/application/NaverOAuthService.java
Labels: bug, fix

#202 [Fix] interview search
  src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/InterviewController.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
  src/main/java/org/hoongoin/interviewbank/interview/enums/CareerYear.java
  src/main/java/org/hoongoin/interviewbank/interview/enums/InterviewPeriod.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
Labels: fix

#204 [Fix] interview update when question size is different from the original
  src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewCommandService.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandService.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/InterviewEntityCommandServiceTest.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandServiceTest.java
Labels: bug, fix

#206 [Refactor] exception message and log
  src/main/java/org/hoongoin/interviewbank/account/application/AccountExternalService.java
  src/main/java/org/hoongoin/interviewbank/account/application/AccountService.java
  src/main/java/org/hoongoin/interviewbank/account/application/GoogleOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/KakaoOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/NaverOAuthService.java
  src/main/java/org/hoongoin/interviewbank/account/application/entity/Account.java
  src/main/java/org/hoongoin/interviewbank/account/controller/GoogleOAuthController.java
  src/main/java/org/hoongoin/interviewbank/account/controller/NaverOAuthController.java
  src/main/java/org/hoongoin/interviewbank/account/domain/AccountCommandService.java
  src/main/java/org/hoongoin/interviewbank/account/domain/AccountQueryService.java
  src/main/java/org/hoongoin/interviewbank/account/domain/PasswordResetTokenQuery.java
  src/main/java/org/hoongoin/interviewbank/exception/IbAccountNotMatchException.java
  src/main/java/org/hoongoin/interviewbank/exception/IbBadRequestException.java
  src/main/java/org/hoongoin/interviewbank/exception/IbEntityExistsException.java
  src/main/java/org/hoongoin/interviewbank/exception/IbEntityNotFoundException.java
  src/main/java/org/hoongoin/interviewbank/exception/IbInternalServerException.java
  src/main/java/org/hoongoin/interviewbank/exception/IbLoginFailedException.java
  src/main/java/org/hoongoin/interviewbank/exception/IbSoftDeleteException.java
  src/main/java/org/hoongoin/interviewbank/exception/IbUnauthorizedException.java
  src/main/java/org/hoongoin/interviewbank/exception/IbValidationException.java
  src/main/java/org/hoongoin/interviewbank/exception/handler/IbControllerAdvice.java
  src/main/java/org/hoongoin/interviewbank/inquiry/application/entity/Inquiry.java
  src/main/java/org/hoongoin/interviewbank/interview/application/InterviewService.java
  src/main/java/org/hoongoin/interviewbank/interview/application/entity/Interview.java
  src/main/java/org/hoongoin/interviewbank/interview/application/entity/Question.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewCommandService.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/JobCategoryQueryService.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/JobCategoryQueryServiceImplementation.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandService.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/QuestionQueryService.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/ScrapAnswerService.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/ScrapService.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/entity/Scrap.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/entity/ScrapAnswer.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/entity/ScrapQuestion.java
  src/main/java/org/hoongoin/interviewbank/scrap/domain/ScrapAnswerCommandService.java
  src/main/java/org/hoongoin/interviewbank/scrap/domain/ScrapAnswerQueryService.java
  src/main/java/org/hoongoin/interviewbank/scrap/domain/ScrapCommandService.java
  src/main/java/org/hoongoin/interviewbank/scrap/domain/ScrapQueryService.java
  src/test/java/org/hoongoin/interviewbank/interview/application/entity/InterviewTest.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/InterviewEntityCommandServiceTest.java
Labels: refactor

#208 [Refactor] Refactor Test Code
  src/test/java/org/hoongoin/interviewbank/account/AccountTestFactory.java
  src/test/java/org/hoongoin/interviewbank/authentication/ScrapAnswerApiAuthentication.java
  src/test/java/org/hoongoin/interviewbank/interview/InterviewTestFactory.java
  src/test/java/org/hoongoin/interviewbank/interview/application/InterviewServiceTest.java
  src/test/java/org/hoongoin/interviewbank/interview/controller/InterviewControllerTest.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/InterviewEntityCommandServiceTest.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandServiceTest.java
  src/test/java/org/hoongoin/interviewbank/interview/domain/QuestionQueryServiceTest.java
  src/test/java/org/hoongoin/interviewbank/interview/infrastructure/entity/InterviewEntityTest.java
  src/test/java/org/hoongoin/interviewbank/scrap/ScrapMapperTest.java
  src/test/java/org/hoongoin/interviewbank/scrap/ScrapTestFactory.java
  src/test/java/org/hoongoin/interviewbank/scrap/application/ScrapServiceTest.java
  src/test/java/org/hoongoin/interviewbank/scrap/controller/ScrapControllerTest.java
Labels: refactor
