Repository Interview-Bank/Interview-Bank-Back, pull requests merged in 2023-08, with the labels that each got.

#263 [Feat] scrap of interview
  src/main/java/org/hoongoin/interviewbank/config/SecurityConfig.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/InterviewQueryService.java
  src/main/java/org/hoongoin/interviewbank/scrap/application/ScrapService.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/ScrapController.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/response/ReadScrapAllOfInterview.java
  src/main/java/org/hoongoin/interviewbank/scrap/domain/ScrapLikeQueryService.java
  src/main/java/org/hoongoin/interviewbank/scrap/domain/ScrapQueryService.java
  src/main/java/org/hoongoin/interviewbank/scrap/infrastructure/repository/ScrapRepository.java
  src/main/java/org/hoongoin/interviewbank/utils/SecurityUtil.java
  src/test/java/org/hoongoin/interviewbank/authentication/ScrapApiAuthentication.java
Labels: feature

#269 [Feat] job category second level
  src/main/java/org/hoongoin/interviewbank/interview/InterviewMapper.java
  src/main/java/org/hoongoin/interviewbank/interview/JobCategoryService.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/JobCategoryController.java
  src/main/java/org/hoongoin/interviewbank/interview/controller/response/GetSecondLevelJobCategoriesResponse.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/JobCategoryQueryService.java
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/JobCategoryRepository.java
  src/test/java/org/hoongoin/interviewbank/authentication/JobCategoryApiAuthentication.java
Labels: feature

#271 [Fix] interview search querydsl
  src/main/java/org/hoongoin/interviewbank/interview/infrastructure/repository/InterviewRepository.java
Labels: bug

#250 [Refactor] thread async setting
  src/main/java/org/hoongoin/interviewbank/config/IbAsyncUncaughtExceptionHandler.java
  src/main/java/org/hoongoin/interviewbank/config/SpringAsyncConfig.java
  src/main/java/org/hoongoin/interviewbank/interview/domain/QuestionCommandServiceAsync.java
  src/main/java/org/hoongoin/interviewbank/utils/MailUtil.java
Labels: refactor

#272 [Fix] add job category to read scrap detail
  src/main/java/org/hoongoin/interviewbank/scrap/application/ScrapService.java
  src/main/java/org/hoongoin/interviewbank/scrap/controller/response/ReadScrapDetailResponse.java
  src/test/java/org/hoongoin/interviewbank/interview/InterviewTestFactory.java
  src/test/java/org/hoongoin/interviewbank/scrap/application/ScrapServiceTest.java
Labels: fix
